ALTER TABLE OFFICE DROP CONSTRAINT fk_Manage;
DROP TABLE EMPLOYEE;
DROP TABLE OFFICE;
DROP TABLE POSITION;

CREATE TABLE POSITION (
  POS_Title VARCHAR2(25),
  POS_Rate INT,
  POS_VacDays INT,
  PRIMARY KEY (POS_Title)
);


CREATE TABLE OFFICE (
  Office# INT,
  Office_StreetAdd VARCHAR2(50),
  Office_City VARCHAR2(50),
  Office_State VARCHAR2(50),
  Office_Zip VARCHAR2(10),
  Manager_ID INT UNIQUE,
  PRIMARY KEY (Office#)
);



CREATE TABLE EMPLOYEE (
  Emp_ID INT,
  Emp_Fname VARCHAR2(25),
  Emp_Lname VARCHAR2(25),
  Emp_MI VARCHAR2(2),
  POS_Title VARCHAR2(25),
  Office# INT,
  Emp_Phone VARCHAR2(10),
  Emp_StartD DATE,
  Emp_StreetAdd VARCHAR2(50),
  Emp_City VARCHAR2(50),
  Emp_State VARCHAR2(50),
  Emp_Zip VARCHAR2(10),
  Emp_DOB DATE,
  PRIMARY KEY (Emp_ID)
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_Pos FOREIGN KEY (POS_Title) REFERENCES POSITION(POS_Title);
ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_Off FOREIGN KEY (Office#) REFERENCES OFFICE(Office#);

--This Foreign key will be added after data is added
--ALTER TABLE OFFICE ADD CONSTRAINT fk_Manage FOREIGN KEY (Manager_ID) REFERENCES EMPLOYEE(Emp_ID);